### ISSUE TITLE
Alex tem um site 

### ISSUE THREAD

**Issue by mateuslourencao** [opedro/alextemumsite#4]
Teste de Bechdel - https://bechdeltest.com/

**Comment by alex3aguiar** [comment]
solved in this PR 
https://github.com/opedro/alextemumsite/pull/5
@opedro 
check out, plz

**Comment by g-barbosa** [comment]
@opedro acho que você esqueceu de fechar essa _issue_
Ela foi resolvida na pr #5, como o Alex mencionou acima
